import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { isAuth } from "@/lib/server-helper";

const geistInter = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
});

const geistMontserrat = Montserrat({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLoggedIn = await isAuth();

  return (
    <html lang="en">
      <body className={`${geistInter.variable} ${geistMontserrat.variable}`}>
        <div className="headerContainer">
          {" "}
          <Header isLoggedIn={isLoggedIn} />
        </div>
        <div className="layout">
          <main className="main-content">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
